services:
  - type: web
    name: hrpilote-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: starter
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: "7"
      - key: DEBUG
        value: "false"
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        sync: false
      - key: EMAIL_FROM
        value: noreply@hrpilot.com
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: REDIS_URL
        sync: false
      - key: UPLOAD_DIR
        value: /var/data/uploads
    disks:
      - name: uploads
        mountPath: /var/data
        sizeGB: 2

  - type: static
    name: hrpilote-frontend
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          name: hrpilote-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
          path: /api/v1
    pullRequestPreviewsEnabled: false
